github: [Cdaprod]
open_collective: thatdam
buy_me_a_coffee: thatdam
patreon: cdaprod
custom:
  - "https://thatdam.io/sponsor"
  - "https://opencollective.com/thatdam"
  - "https://github.com/sponsors/Cdaprod"
