name: Sponsors • Rewrite Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  rewrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout control repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Generate SPONSORS.md with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/rewrite_sponsors_page.py \
            --funding docs/FUNDING.md \
            --policy policy/sponsors.yaml \
            --template templates/sponsors_page_prompt.md \
            --output docs/SPONSORS.md
      - name: Splice README sponsors section
        run: bash scripts/splice_readme_sponsors.sh
      - name: Commit (control repo baseline)
        run: |
          if git diff --quiet; then
            echo "No changes in control repo."
          else
            git config user.name "cdaprod-bot"
            git config user.email "bot@users.noreply.github.com"
            git add docs/SPONSORS.md README.md || true
            git commit -m "docs(sponsors): rewrite via OpenAI agent"
            git push
          fi

  delegate:
    runs-on: ubuntu-latest
    needs: rewrite
    steps:
      - uses: actions/checkout@v4
      - name: App Installation Token
        id: app
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Auth gh
        run: echo "${{ steps.app.outputs.token }}" | gh auth login --with-token
      - name: Open PRs to target repos
        env:
          TOKEN: ${{ steps.app.outputs.token }}
        run: |
          set -euo pipefail
          targets=("Cdaprod/ThatDAMToolbox")
          for repo in "${targets[@]}"; do
            work="work/${repo}"
            mkdir -p "$(dirname "$work")"
            git clone "https://x-access-token:${TOKEN}@github.com/${repo}.git" "$work" --quiet
            cp -f docs/SPONSORS.md "$work/docs/SPONSORS.md"
            mkdir -p "$work/.github"
            cp -f .github/FUNDING.yml "$work/.github/FUNDING.yml"
            pushd "$work" >/dev/null
            git checkout -B codex-ops/sponsors-rewrite
            bash ../../scripts/splice_readme_sponsors.sh || true
            git add docs/SPONSORS.md .github/FUNDING.yml README.md || true
            if git diff --cached --quiet; then
              echo "No sponsor page changes for $repo"
            else
              git -c user.name="cdaprod-bot" -c user.email="bot@users.noreply.github.com" commit -m "docs(sponsors): rewrite Sponsors page (agent-sync)"
              git push -u origin codex-ops/sponsors-rewrite --force
              gh pr create --title "Rewrite Sponsors page" \
                --body "Auto-generated by Codex-Ops using OpenAI agent.\n\n- Aligns with FUNDING.yml\n- Updates docs/SPONSORS.md\n- Splices README sponsors section" \
                --base main --head codex-ops/sponsors-rewrite || true
            fi
            popd >/dev/null
          done
